---
- name: remove old, failing config
  lineinfile:
    name: "/etc/apt/sources.list.d/pgdg.list"
    line: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: absent

- name: remove old apt source without valid key
  lineinfile:
    name: "/etc/apt/sources.list.d/apt_datadoghq_com.list"
    line: "deb https://apt.datadoghq.com/ stable 6"
    state: absent

- name: configure datadog agent
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ datadog_key }}"
    datadog_config:
      hostname: "{{ inventory_hostname }}"
      tags:
        - "env:{{ rails_env }}"
        - "host-id:{{ host_id | default(ansible_limit) }}"
      logs_enabled: false
      apm_config:
        enabled: false
    datadog_config_ex:
      trace.config:
        env: "{{ rails_env }}"
    datadog_enabled: false
  when: datadog_key is defined

- name: set up postgres stats collection
  import_tasks: pg_stats.yml
  when: datadog_key is defined and datadog_db_password is defined

- name: set up nginx stats collection
  import_tasks: nginx_stats.yml
  when: datadog_key is defined

- name: disable datadog agent
  service:
    name: datadog-agent
    state: stopped
  when: disable_datadog is defined
