---

- name: upload assets
  synchronize:
    src: "{{ local_asset_path }}/{{ migrate_dir }}"
    dest: "{{ dest_path }}/"
    mode: push
    rsync_opts:
      - "--chown={{ app_user }}:{{ app_user }}"
  become: yes
  become_user: "{{ app_user }}"
