---

- name: provision sidekiq service
  template:
    src: "sidekiq.service.j2"
    dest: "/etc/systemd/system/sidekiq.service"
    mode: "0644"
  become: yes
  notify: reload systemd

- name: enable sidekiq unit
  service:
    name: "sidekiq"
    enabled: yes
  become: yes
