--- # App

# Setup shared files and folders

- name: make dirs
  file:
    path={{ item }}
    state=directory
    owner={{ app_user }}
  with_items:
    - "{{ app_path }}"
    - "{{ shared_path }}"
    - "{{ backup_path }}"
    - "{{ releases_path }}"
    - "{{ system_path }}"
    - "{{ images_path }}"
    - "{{ files_path }}"
    - "{{ storage_path }}"
    - "{{ spree_path }}"
    - "{{ log_path }}"
    - "{{ pid_path }}"
    - "{{ sock_path }}"
    - "{{ config_path }}"
  tags: dirs

- name: template files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ app_user }}
    mode=0775
  with_items:
    - { src: "application.yml.j2", dest: "{{ config_path }}/application.yml" }
    - { src: "env.j2", dest: "{{ config_path }}/.env.{{ rails_env }}" }
    - { src: "postgresql.yml.j2", dest: "{{ config_path }}/database.yml" }
  tags: app_templates

- name: get l10n repo
  git:
    repo={{ l10n_repo }}
    dest={{ l10n_path }}
    version={{ l10n_git_version }}
    force=yes
  tags: l10n

- name: clear default rbenv vars
  file:
    dest: "{{ app_user_home_path }}/.rbenv/vars"
    state: absent
  become: yes
