--- # webserver

- name: provision service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  become: yes
  with_items:
    - { src: "puma.service.j2", dest: "/etc/systemd/system/puma.service" }
  register: app_service_files
  notify:
    - restart puma if running
  tags: init

- name: provision puma config
  template:
    src: "puma.rb.j2"
    dest: "{{ config_path }}/puma.rb"
    mode: 0644
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when: app_service_files.changed
  tags:
    - init
    - skip_ansible_lint # The alternative involves flushing all handlers at this point, and we don't want to

- name: Enable puma unit
  service:
    name: puma
    enabled: yes
  become: yes
  tags: init

