---
# Enables integrations with 3rd party apps such as Zapier or Metabase.
# Creates a database user with restricted access to the database and
# configures postgres to allow limited access on external connections.

- name: Integration setup
  hosts: ofn_servers
  remote_user: "{{ user }}"
  become: yes
  vars:
    postgresql_restarted_state: "restarted"

  pre_tasks:
    - include_role:
        name: check_secrets

  handlers:
    - include: ../roles/shared_handlers/handlers/main.yml

  roles:
    - role: dbserver
      become: yes
      become_user: root
      tags: dbserver

  tasks:
    - name: Apply integrations settings
      include_role:
        name: db_integrations
      vars:
        db_integration: "{{ integration_item }}"
      loop: "{{ db_integrations }}"
      loop_control:
        loop_var: integration_item
      when: db_integrations is defined
